"""Crear tablas iniciales

Revision ID: 311f30013f62
Revises: 
Create Date: 2026-04-06 22:56:30.889483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311f30013f62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatibilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refaccion_id', sa.Integer(), nullable=False),
    sa.Column('moto_modelo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['refaccion_id'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moto', schema=None) as batch_op:
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moto', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('modelo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    op.drop_table('compatibilidad')
    # ### end Alembic commands ###
