"""Simplificar nomina a solo sueldo

Revision ID: 9900426dd936
Revises: 6f045d63f32f
Create Date: 2026-04-10 10:25:54.483106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9900426dd936'
down_revision = '6f045d63f32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.drop_column('fecha')
        batch_op.drop_column('empleado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleado', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
