"""add cliente extra fields

Revision ID: bd8b40359ee3
Revises: 4e4177d05b1a
Create Date: 2026-04-07 22:39:27.657326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8b40359ee3'
down_revision = '4e4177d05b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        # Ya existen las columnas, no se añaden de nuevo
        pass

    with op.batch_alter_table('moto', schema=None) as batch_op:
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('presupuesto', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               nullable=True)
        # Elimina solo la columna, sin drop_constraint
        batch_op.drop_column('producto_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presupuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'inventario', ['producto_id'], ['id'])
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('moto', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('modelo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    # No se eliminan columnas de cliente porque ya existían
    # ### end Alembic commands ###
